project:
  type: website

website:
  title: "PUBLIC INNOVATION, DEVELOPMENT AND SUSTAINABILITY CONFERENCE"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Speakers"
        href: speakers.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: default
    css: styles.css

